name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'illallangi/$(system.TeamProject):$(build.SourceVersion)'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: '$(imageName)'
- task: Docker@1
  displayName: Login
  inputs:
    command: login
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: '$(imageName)'
