name: $(build.SourceVersion)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'illallangi/$(system.TeamProject):latest'
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'illallangi/$(system.TeamProject):$(Date:yyyyMMdd)'
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'illallangi/$(system.TeamProject):$(build.SourceVersion)'
- task: Docker@1
  displayName: Login
  inputs:
    command: login
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: 'illallangi/$(system.TeamProject):latest'
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: 'illallangi/$(system.TeamProject):$(Date:yyyyMMdd)'
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: 'illallangi/$(system.TeamProject):$(build.SourceVersion)'
