name: $(build.SourceVersion)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Docker@1
  displayName: 'Build an image'
  strategy:
    matrix:
      naked:
        imageName: 'illallangi/$(system.TeamProject)'
      date:
        imageName: 'illallangi/$(system.TeamProject):$(Date:yyyyMMdd)'
      version:
        imageName: 'illallangi/$(system.TeamProject):$(build.SourceVersion)'

- task: Docker@1
  displayName: Login
  inputs:
    command: login
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: dockerhub
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: '$(imageName)'
#    imageName: 'illallangi/$(system.TeamProject):latest'
#    imageName: 'illallangi/$(system.TeamProject):$(Date:yyyyMMdd)'
#    imageName: 'illallangi/$(system.TeamProject):$(build.SourceVersion)'
#    imageName: 'illallangi/$(system.TeamProject):$(build.SourceVersion)'
